### ISSUE TITLE
*Subject: Important Update: GirlScript Summer of Code Project Status*

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [swaraj-das/Collect-your-GamingTools#164]
Dear Project Admins,

We are reaching out to you regarding the status of your project in the GirlScript Summer of Code program. We have noticed that there has been a period of inactivity on your project's repository.

We understand that unexpected circumstances can arise, and we want to ensure that your project continues to be a part of program. Please let us know if you would like to continue with your project. If so, we would appreciate it if you could actively participate.

If you have decided to discontinue your project, please let us know as soon as possible so that we can make necessary adjustments to the program.

Thank you for your understanding and cooperation.

The GirlScript Summer of Code Team

**Comment by swaraj-das** [comment]
Dear GirlScript Summer of Code Team,

Thank you for reaching out regarding the status of my project.

I want to confirm that I am still committed to the project and do not intend to discontinue it. There was a brief period of inactivity (1-2 days) due to academic commitments and because I haven't received any help from the mentors, despite reaching out to them.

As a project admin, I am managing both my studies and the project, and I hope this is understood. I will work on increasing activity on the repository and moving the project forward.

Thank you for your understanding. I look forward to continuing with the project, and any additional support or guidance from mentors would be greatly appreciated.

Best regards,
Swaraj Das

**Comment by AKSHITHA-CHILUKA** [comment]
Please tag your mentors here @swaraj-das 
As we are reviewing all the inactive mentors and going to remove them if the inactive period continues , and we will assign you new mentors

**Comment by AKSHITHA-CHILUKA** [comment]
also gssoc-extd is invalid label

**Comment by swaraj-das** [comment]
> also gssoc-extd is invalid label

I edited the label from yaml file.

**Comment by swaraj-das** [comment]
> Please tag your mentors here @swaraj-das As we are reviewing all the inactive mentors and going to remove them if the inactive period continues , and we will assign you new mentors

@Suruchibharti @IshaChouhan01
