### ISSUE TITLE
[Feature] to add a light and dark mode toggle new 3d version 

### ISSUE THREAD

**Issue by sv410** [swaraj-das/Collect-your-GamingTools#361]
### Description

to add a light and dark mode toggle new 3d version 

### Screenshots

![WhatsApp Image 2024-10-12 at 11 20 20 PM (1)](https://github.com/user-attachments/assets/f1c5f4f8-d155-4b43-8636-3a76cba2c0da)
![WhatsApp Image 2024-10-12 at 11 19 35 PM (1)](https://github.com/user-attachments/assets/56121a09-b43f-410e-8171-00da339ae1a0)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by swaraj-das** [comment]
@sv410 @sv410 You made the pull request **from the `sv410-patch-1` branch to your forked repository's `main` branch**, which is why I am unable to review or merge the code. **You should create a PR from your `sv410-patch-1` branch to the `main` branch of my repository, i.e., swaraj-das/Collect-your-GamingTools.**

I can't check, or merge, or add any level if you don't create pull request to my main branch.

**Comment by swaraj-das** [comment]
I commented 2 days ago in one of your PR. 
And you should add the 3 files together in one PR. Anyone can't check the 3 files separately in 3 PRs.
